apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: n8n-config
                  key: DB_POSTGRESDB_DATABASE
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: n8n-config
                  key: DB_POSTGRESDB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: DB_POSTGRESDB_PASSWORD
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: n8n-config
                  key: DB_POSTGRESDB_HOST
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: n8n-config
                  key: DB_POSTGRESDB_PORT
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: n8n-config
                  key: DB_POSTGRESDB_DATABASE
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: n8n-config
                  key: DB_POSTGRESDB_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: DB_POSTGRESDB_PASSWORD
            - name: PGTZ
              valueFrom:
                configMapKeyRef:
                  name: n8n-config
                  key: GENERIC_TIMEZONE
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready","-U","n8n","-d","n8n","-h","127.0.0.1","-p","5432"]
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 12
          startupProbe:
            exec:
              command: ["pg_isready","-U","n8n","-d","n8n","-h","127.0.0.1","-p","5432"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pg-data
